import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { animate } from "motion";
import { useEffect, useRef } from "react";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Box />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

function Box(): React.ReactElement {
  const divRef = useRef(null);
  useEffect(() => {
    if (divRef.current) {
      console.log("animate me");
      animate(
        divRef.current,
        {
          transform: [
            "none",
            "rotate(47deg)",
            "rotate(86deg)",
            "rotate(41deg)",
            "rotate(3deg)",
            "rotate(-41deg)",
            "rotate(-86deg)",
            "rotate(-43deg)",
            "none",
          ],
        },
        {
          repeat: Infinity,
          duration: 10,
        }
      );
      animate(
        divRef.current,
        {
          backgroundColor: [
            "red",
            "orange",
            "yellow",
            "green",
            "blue",
            "indigo",
            "violet",
          ],
          fontFamily: ["Papyrus", "Comic Sans MS", "times", "sans-serif"],
        },
        {
          repeat: Infinity,
          duration: 13,
          direction: "alternate",
        }
      );
    }
  }, [divRef.current]);
  return (
    <div
      ref={divRef}
      style={{
        backgroundColor: "red",
        width: "500px",
        height: "500px",
        textAlign: "center",
        alignItems: "center",
        justifyContent: "center",
        display: "flex",
        fontSize: "144px",
        fontFamily: "Papyrus, 'Comic Sans', times, serif",
        color: "white",
      }}
    >
      hello ty
    </div>
  );
}

export default Home;
